"void" use of unused variable captured in lambda.
When using -Werror, this unused variable was breaking compilation.
error: unused variable ‘fn’ [-Werror=unused-variable]